ChartValues: {}
HelmChartPath: chart
RuntimeType: Kubernetes
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/quickstart-airflow
RegionId: cn-hangzhou
OutputType: HelmNotes
Owner: yehanyh
Branch: main
Platform: github
